query allFiles($searchStr: String, $orderBy: String){
  allFiles(searchStr: $searchStr, orderBy: $orderBy) {
        filename
        exists
		size
		modified
		isFolder
		tarballCreated
		fileType
  }
}
