{
  allFiles {
    id
    file
    filename
    fileDiscovered
    exists
    size
    modified
    isFolder
    fileType
    secureLink {
      id
      url
      linkDeadline
      user {
        profile {
          urlTtl
        }
      }
    }
  }
}
