query allFiles($search: String){
  allFiles(search: $search) {
    id
    file
    filename
    fileDiscovered
    exists
    size
    modified
    isFolder
    fileType
    minTtl
    maxTtl
    secureLink {
      id
      url
      linkDeadline
      user {
        profile {
          urlTtl
        }
      }
    }
  }
}
