# Generated by Django 2.2.1 on 2019-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(editable=False, max_length=255, path='/opt/services/django_nginx_secure_link/secure_link_files', unique=True, verbose_name='Путь до файла')),
                ('secure_link', models.URLField(blank=True, editable=False, null=True, verbose_name='Публичная ссылка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
