# Generated by Django 2.2.1 on 2019-05-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания ссылки'),
        ),
    ]
