# Generated by Django 2.2.2 on 2019-06-21 06:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190621_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_ttl',
            field=models.PositiveIntegerField(default=432000, validators=[django.core.validators.MinValueValidator(86400), django.core.validators.MaxValueValidator(2592000)], verbose_name='Время жизни ссылки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
