# Generated by Django 2.2.2 on 2019-06-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190621_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileSystem',
        ),
    ]
