# Generated by Django 2.2.2 on 2019-06-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_filesystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securelink',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='SecureLink',
        ),
    ]
