# Generated by Django 2.2.3 on 2019-07-12 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20190627_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(editable=False, max_length=255, verbose_name='Имя файла')),
                ('secure_url', models.URLField(editable=False)),
                ('who_creates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
