# Generated by Django 2.2.3 on 2019-07-12 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_securelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='securelink',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
